import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ThemeProvider } from '@/components/theme-provider';
import { SanityLive } from '@/sanity/lib/live';
import { ClerkProvider } from '@clerk/nextjs';
import { SidebarProvider } from '@/components/providers/sidebar-provider';
export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};
export default function DashboardLayout({ children, }) {
    return (_jsxs(ClerkProvider, { children: [_jsx(ThemeProvider, { attribute: 'class', defaultTheme: 'system', enableSystem: true, disableTransitionOnChange: true, children: _jsx(SidebarProvider, { children: _jsx("div", { className: 'h-full', children: children }) }) }), _jsx(SanityLive, {})] }));
}
